"use client";

import { FileText } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { adminApi, type SystemSkill } from "../lib/admin-client";
import { useInteractionDialog } from "./interaction-dialog-provider";
import { usePreferences } from "./preferences-provider";

const label = (zh: boolean, cn: string, en: string) => zh ? cn : en;
function Shell({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="space-y-4" aria-label={title}><div><h3 className="text-sm font-semibold text-primary">{title}</h3><p className="mt-1 text-xs text-secondary">{description}</p></div>{children}</section>; }
function Chip({ children }: { children: React.ReactNode }) { return <span className="rounded-sm bg-subtle px-1.5 py-0.5 text-[11px] text-secondary">{children}</span>; }
function SmallAction({ children, onClick, danger = false, disabled = false }: { children: React.ReactNode; onClick: () => void; danger?: boolean; disabled?: boolean }) { return <button type="button" onClick={onClick} disabled={disabled} className={`min-h-9 px-2.5 text-xs ${danger ? "text-[var(--danger)]" : "text-primary hover:bg-subtle"} disabled:opacity-45`}>{children}</button>; }

export { AdminUsersPanelEnhanced } from "./admin-users-panel";

export function AdminSkillsPanelEnhanced({ onDirtyChange }: { onDirtyChange?: (dirty: boolean) => void }) {
  const { resolvedLocale } = usePreferences(); const zh = resolvedLocale === "zh-CN"; const { confirm } = useInteractionDialog(); const [items, setItems] = useState<SystemSkill[]>([]); const [content, setContent] = useState<Record<string, string>>({}); const [error, setError] = useState(""); const [draft, setDraft] = useState({ category: "EXPORT_CONTEXT", locale: "zh-CN", name: "", content: "" });
  useEffect(() => { onDirtyChange?.(Boolean(draft.name.trim() || draft.content.trim())); }, [draft.name, draft.content, onDirtyChange]);
  const load = useCallback(async () => { try { setItems(await adminApi.systemSkills()); } catch (e) { setError(e instanceof Error ? e.message : "Load failed"); } }, []); useEffect(() => { void load(); }, [load]);
  const view = async (item: SystemSkill) => { try { const result = item.is_customized ? await adminApi.systemSkill(item.id) : null; const text = result?.content ?? (item.builtin_content_url ? await (await fetch(item.builtin_content_url)).text() : ""); setContent((v) => ({ ...v, [item.id]: text })); } catch (e) { setError(e instanceof Error ? e.message : "Load failed"); } };
  const create = async () => { if (!draft.name.trim() || !draft.content.trim()) return; try { await adminApi.createSystemSkill({ ...draft, default_enabled: false }); setDraft((v) => ({ ...v, name: "", content: "" })); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Create failed"); } };
  const change = async (item: SystemSkill, action: "toggle" | "restore" | "delete") => { if (action === "delete" && !(await confirm({ title: label(zh, "删除系统 Skill", "Delete system skill"), description: label(zh, "内置默认仍会保留。", "The bundled default remains available."), confirmLabel: label(zh, "删除", "Delete"), danger: true }))) return; try { if (action === "toggle") await adminApi.updateSystemSkill(item.id, { status: item.status === "ACTIVE" ? "DISABLED" : "ACTIVE" }); else if (action === "restore") await adminApi.restoreSystemSkill(item.id); else await adminApi.deleteSystemSkill(item.id); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Action failed"); } };
  return <Shell title={label(zh, "系统 Skill", "System skills")} description={label(zh, "管理默认 Skill、覆盖版本和启停状态。", "Manage bundled skills, overrides, and availability.")}><div className="space-y-3 border border-ui bg-subtle p-3"><p className="text-xs font-semibold text-primary">{label(zh, "创建管理员 Skill", "Create admin system skill")}</p><div className="grid grid-cols-2 gap-2"><select value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })} className="input-base min-h-9 px-2 text-xs"><option value="EXPORT_CONTEXT">Export context</option><option value="CONVERSATION_RESCUE">Conversation rescue</option></select><select value={draft.locale} onChange={(e) => setDraft({ ...draft, locale: e.target.value })} className="input-base min-h-9 px-2 text-xs"><option value="zh-CN">中文</option><option value="en">English</option></select></div><input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} placeholder={label(zh, "名称", "Name")} className="input-base min-h-9 w-full px-2 text-xs" /><textarea value={draft.content} onChange={(e) => setDraft({ ...draft, content: e.target.value })} placeholder={label(zh, "纯文本 Markdown 内容", "Plain-text Markdown content")} className="input-base min-h-24 w-full p-2 text-xs" /><button type="button" onClick={() => void create()} className="btn-primary min-h-9 px-3 text-xs">{label(zh, "创建", "Create")}</button></div><div className="divide-y divide-[var(--border)]">{items.map((item) => <div key={item.id} className="py-3"><div className="flex flex-wrap items-center gap-2"><FileText className="h-4 w-4 text-secondary" /><span className="min-w-0 flex-1 truncate text-sm font-medium text-primary">{item.name}</span><Chip>{item.status}</Chip><Chip>{item.source_kind === "BUNDLED" ? label(zh, "内置", "Bundled") : label(zh, "管理员", "Admin")}</Chip><SmallAction onClick={() => void view(item)}>{label(zh, "查看", "View")}</SmallAction>{item.source_kind === "BUNDLED" ? <SmallAction onClick={() => void change(item, "restore")}>{label(zh, "恢复", "Restore")}</SmallAction> : <><SmallAction onClick={() => void change(item, "toggle")}>{item.status === "ACTIVE" ? label(zh, "停用", "Disable") : label(zh, "启用", "Enable")}</SmallAction><SmallAction danger onClick={() => void change(item, "delete")}>{label(zh, "删除", "Delete")}</SmallAction></>}</div>{content[item.id] !== undefined ? <pre className="mt-2 max-h-48 overflow-auto border border-ui bg-subtle p-2 text-xs text-primary">{content[item.id]}</pre> : null}</div>)}</div>{error ? <p role="alert" className="text-sm text-[var(--danger)]">{error}</p> : null}</Shell>;
}
