"""Derived Context candidates, immutable revisions and binding receipts."""
from alembic import op
import sqlalchemy as sa

revision = "20261002_0044"
down_revision = "20261002_0043"
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_member_objects',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=240), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sha256'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('context_bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('identity_digest', sa.String(length=64), nullable=False),
    sa.Column('identity', sa.JSON(), nullable=False),
    sa.Column('locator_mapping', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'identity_digest', name='uq_context_binding_identity')
    )
    op.create_index(op.f('ix_context_bindings_conversation_id'), 'context_bindings', ['conversation_id'], unique=False)
    op.create_table('context_export_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('raw_revision', sa.BigInteger(), nullable=False),
    sa.Column('projection', sa.JSON(), nullable=False),
    sa.Column('message_versions', sa.JSON(), nullable=False),
    sa.Column('fingerprints', sa.JSON(), nullable=False),
    sa.Column('dependency_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_export_receipts_conversation_id'), 'context_export_receipts', ['conversation_id'], unique=False)
    op.create_table('continuation_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('branch_key', sa.String(length=64), nullable=False),
    sa.Column('protocol_revision', sa.String(length=160), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('declared_trust', sa.String(length=40), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('current_sha256', sa.String(length=64), nullable=False),
    sa.Column('index_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_sha256'], ['context_member_objects.sha256'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['index_sha256'], ['context_member_objects.sha256'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['continuation_revisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'branch_key', 'protocol_revision', name='uq_continuation_protocol_revision'),
    sa.UniqueConstraint('conversation_id', 'digest', name='uq_continuation_revision_content')
    )
    op.create_index(op.f('ix_continuation_revisions_conversation_id'), 'continuation_revisions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_continuation_revisions_current_sha256'), 'continuation_revisions', ['current_sha256'], unique=False)
    op.create_index(op.f('ix_continuation_revisions_index_sha256'), 'continuation_revisions', ['index_sha256'], unique=False)
    op.create_table('continuation_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('base_revision_id', sa.Uuid(), nullable=True),
    sa.Column('base_generation', sa.BigInteger(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_sha256', sa.String(length=64), nullable=True),
    sa.Column('index_sha256', sa.String(length=64), nullable=True),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('inherited_members', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('input_revision >= 1 AND base_generation >= 0', name='ck_continuation_candidate_versions'),
    sa.ForeignKeyConstraint(['base_revision_id'], ['continuation_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_sha256'], ['context_member_objects.sha256'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['index_sha256'], ['context_member_objects.sha256'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manifest_sha256'], ['context_member_objects.sha256'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'idempotency_key', name='uq_continuation_candidate_request')
    )
    op.create_index(op.f('ix_continuation_candidates_conversation_id'), 'continuation_candidates', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_continuation_candidates_current_sha256'), 'continuation_candidates', ['current_sha256'], unique=False)
    op.create_index(op.f('ix_continuation_candidates_index_sha256'), 'continuation_candidates', ['index_sha256'], unique=False)
    op.create_index(op.f('ix_continuation_candidates_manifest_sha256'), 'continuation_candidates', ['manifest_sha256'], unique=False)
    op.create_table('continuation_states',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('generation', sa.BigInteger(), nullable=False),
    sa.Column('adopted_revision_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('generation >= 0', name='ck_continuation_generation'),
    sa.ForeignKeyConstraint(['adopted_revision_id'], ['continuation_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('continuation_validations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('raw_revision', sa.BigInteger(), nullable=False),
    sa.Column('checker_version', sa.String(length=64), nullable=False),
    sa.Column('input_digest', sa.String(length=64), nullable=False),
    sa.Column('runtime_state', sa.String(length=40), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['continuation_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_continuation_validations_candidate_id'), 'continuation_validations', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_continuation_validations_candidate_id'), table_name='continuation_validations')
    op.drop_table('continuation_validations')
    op.drop_table('continuation_states')
    op.drop_index(op.f('ix_continuation_candidates_manifest_sha256'), table_name='continuation_candidates')
    op.drop_index(op.f('ix_continuation_candidates_index_sha256'), table_name='continuation_candidates')
    op.drop_index(op.f('ix_continuation_candidates_current_sha256'), table_name='continuation_candidates')
    op.drop_index(op.f('ix_continuation_candidates_conversation_id'), table_name='continuation_candidates')
    op.drop_table('continuation_candidates')
    op.drop_index(op.f('ix_continuation_revisions_index_sha256'), table_name='continuation_revisions')
    op.drop_index(op.f('ix_continuation_revisions_current_sha256'), table_name='continuation_revisions')
    op.drop_index(op.f('ix_continuation_revisions_conversation_id'), table_name='continuation_revisions')
    op.drop_table('continuation_revisions')
    op.drop_index(op.f('ix_context_export_receipts_conversation_id'), table_name='context_export_receipts')
    op.drop_table('context_export_receipts')
    op.drop_index(op.f('ix_context_bindings_conversation_id'), table_name='context_bindings')
    op.drop_table('context_bindings')
    op.drop_table('context_member_objects')
    # ### end Alembic commands ###
